# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3664e8942dc6ea2533518c14d835d0b07947821bdf0bd399596b701c6796e57ff14009ba423338c76fd4f1603bc9358487af0f28e14d0fdc8dea7ed133d87023

test:
  secret_key_base: cb028c2984c9d6b55b5d577526fb5e2b9dd6fad385fa197187c7968e3a7086d9b487a593585c7480bf57f1a76e0479686de9848afa898dd2d9279b3da58a2488

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
